<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'judul'        => "The Faraway Paladin : The Boy in the City of the Dead",  
                'penulis'      => "Kanata Yanagino",  
                'penerbit'     => "	J-Novel Club",  
                'deskripsi'    => "In a city of the dead, long since ruined and far from human civilization, lives a single human child. His name is Will, and he's being raised by three undead: the hearty skeletal warrior, Blood; the graceful mummified priestess, Mary; and the crotchety spectral sorcerer, Gus. The three pour love into the boy, and teach him all they know. But one day, Will starts to wonder: 'Who am I?'",  
                'gambar'       => "1678629299640dd9b31da57.JPG",  
                'harga'        => 350000,  
                'discount'     => 20,  
                'jumlah_halaman'=> 266,  
                'berat'        => 560,  
                'qty'          => 7,  
                'slug'         => "the-faraway-paladin-the-boy-in-the-city-of-the-dead",
                'category_id'  => 1,
            ],
            [
                'judul'        => "A Game of Thrones - A Song of Ice and Fire Book 1",  
                'penulis'      => "George R.R. Martin",  
                'penerbit'     => "HarperCollins Publishers",  
                'deskripsi'    => "As Warden of the north, Lord Eddard Stark counts it a curse when King Robert bestows on him the office of the Hand. His honour weighs him down at court where a true man does what he will, not what he must ... and a dead enemy is a thing of beauty. The old gods have no power in the south, Stark's family is split and there is treachery at court. Worse, the vengeance-mad heir of the deposed Dragon King has grown to maturity in exile in the Free Cities. He claims the Iron Throne.",  
                'gambar'       => "9780007448036.jpg",  
                'harga'        => 450000,  
                'discount'     => 10,  
                'jumlah_halaman'=> 816,  
                'berat'        => 560,  
                'qty'          => 5,  
                'slug'         => "a-game-of-thrones-a-song-of-ice-and-fire-book-1",
                'category_id'  => 1,
            ],
            [
                'judul'        => "A Clash of Kings - A Song of Ice and Fire Book 2",  
                'penulis'      => "George R.R. Martin",  
                'penerbit'     => "HarperCollins Publishers",   
                'deskripsi'    => "As a prophecy of doom cuts across the sky - a comet the colour of blood and flame - five factions struggle for control of a divided land. Brother plots against brother and the dead rise to walk in the night. Against a backdrop of incest, fratricide, alchemy and murder, the price of glory is measured in blood.",  
                'gambar'       => "9780007447831.jpg",  
                'harga'        => 170000,  
                'discount'     => 0,  
                'jumlah_halaman'=> 928,  
                'berat'        => 640,  
                'qty'          => 5,  
                'slug'         => "a-clash-of-kings-a-song-of-ice-and-fire-book-2",
                'category_id'  => 1,
            ],
            [
                'judul'        => "Pride and Prejudice",  
                'penulis'      => "Jane Austen",  
                'penerbit'     => "Penguin Random House Children's UK",  
                'deskripsi'    => "When two rich young gentlemen move to town, they don't go unnoticed - especially when Mrs Bennett vows to have one of her five daughters marry into their fortunes. But love, as Jane and Elizabeth Bennett soon discover, is rarely straightforward, and often surprising. It's only a matter of time until their own small worlds are turned upside down and they discover that first impressions can be the most misleading of all.",  
                'gambar'       => "9780141330167.jpg",  
                'harga'        => 110000,  
                'discount'     => 0,  
                'jumlah_halaman'=> 464,  
                'berat'        => 287,  
                'qty'          => 20,  
                'slug'         => "pride-and-prejudice",
                'category_id'  => 2,
            ],
            [
                'judul'        => "It Starts With Us",  
                'penulis'      => "Colleen Hoover",  
                'penerbit'     => "Simon & Schuster Ltd",  
                'deskripsi'    => "Lily and her ex-husband, Ryle, have just settled into a civil co-parenting rhythm when she suddenly bumps into her first love, Atlas, again. After nearly two years separated, she is elated that for once, time is on their side, and she immediately says yes when Atlas asks her on a date. But her excitement is quickly hampered by the knowledge that, though they are no longer married, Ryle is still very much a part of her life - and Atlas Corrigan is the one man he will hate being in his ex-wife and daughter's life.",  
                'gambar'       => "9781398518162.jpg",  
                'harga'        => 200000,  
                'discount'     => 30,  
                'jumlah_halaman'=> 336,  
                'berat'        => 420,  
                'qty'          => 10,  
                'slug'         => "it-starts-with-us",
                'category_id'  => 2,
            ],
            [
                'judul'        => "And Then There Were None",  
                'penulis'      => "Agatha Christie",  
                'penerbit'     => "HarperCollins Publishers",  
                'deskripsi'    => "1939. Europe teeters on the brink of war. Ten strangers are invited to Soldier Island, an isolated rock near the Devon coast. Cut off from the mainland, with their generous hosts Mr and Mrs U.N. Owen mysteriously absent, they are each accused of a terrible crime. When one of the party dies suddenly they realise they may be harbouring a murderer among their number.",  
                'gambar'       => "9780008123208.jpg",  
                'harga'        => 145000,  
                'discount'     => 70,  
                'jumlah_halaman'=> 256,  
                'berat'        => 180,  
                'qty'          => 5,  
                'slug'         => "and-then-there-were-none",
                'category_id'  => 3,
            ],
            [
                'judul'        => "Dua Dini Hari",  
                'penulis'      => "Chandra Bientang",  
                'penerbit'     => "Noura Books",  
                'deskripsi'    => "Tiga anak jalanan ditemukan tewas, tergantung di pinggir flyover kawasan Jatinegara. Satu mayat lagi menyusul, kali ini terlilit kabel tiang listrik. Penyelidikan dimulai dengan enggan, para polisi bertindak meski jauh dari kata maksimal. Pemikiran semua orang sama: mereka hanya gelandangan, lebih baik disingkirkan.",  
                'gambar'       => "50078136.jpg",  
                'harga'        => 64000,  
                'discount'     => 0,  
                'jumlah_halaman'=> 248,  
                'berat'        => 240,  
                'qty'          => 15,  
                'slug'         => "dua-dini-hari",
                'category_id'  => 3,
            ],
            [
                'judul'        => "The Mist",  
                'penulis'      => "Stephen King",  
                'penerbit'     => "Hodder & Stoughton",  
                'deskripsi'    => "Following a freak summer storm, David Drayton, his son Billy, and their neighbour Brent Norton join dozens of others and head to the local grocery store to replenish supplies. Once there, they become trapped by a strange mist that has enveloped the town. Violent forces concealed in the mist are starting to emerge. And there is another shocking threat from within - one group of survivors, led by a religious zealot, is calling for a sacrifice. Now David and his son must try to escape. But what's outside may be even more dangerous.",  
                'gambar'       => "9781529379310.jpg",  
                'harga'        => 120000,  
                'discount'     => 10,  
                'jumlah_halaman'=> 192,  
                'berat'        => 140,  
                'qty'          => 5,  
                'slug'         => "the-mist",
                'category_id'  => 4,
            ],
            [
                'judul'        => "Dune",  
                'penulis'      => "Frank Herbert",  
                'penerbit'     => "Hodder & Stoughton",  
                'deskripsi'    => "Melange, or 'spice', is the most valuable - and rarest - element in the universe; a drug that does everything from increasing a person's life-span to making interstellar travel possible. And it can only be found on a single planet: the inhospitable desert world Arrakis. Whoever controls Arrakis controls the spice. And whoever controls the spice controls the universe. When the Emperor transfers stewardship of Arrakis from the noble House Harkonnen to House Atreides, the Harkonnens fight back, murdering Duke Leto Atreides. Paul, his son, and Lady Jessica, his concubine, flee into the desert. On the point of death, they are rescued by a band for Fremen, the native people of Arrakis, who control Arrakis' second great resource: the giant worms that burrow beneath the burning desert sands.",  
                'gambar'       => "9780340960196.jpg",  
                'harga'        => 160000,  
                'discount'     => 5,  
                'jumlah_halaman'=> 592,  
                'berat'        => 407,  
                'qty'          => 5,  
                'slug'         => "dune",
                'category_id'  => 5,
            ],
            [
                'judul'        => "I Had That Same Dream Again",  
                'penulis'      => "Yoru Sumino",  
                'penerbit'     => "Seven Seas Entertainment, LLC",  
                'deskripsi'    => "1939. Europe teeters on the brink of war. Ten strangers are invited to Soldier Island, an isolated rock near the Devon coast. Cut off from the mainland, with their generous hosts Mr and Mrs U.N. Owen mysteriously absent, they are each accused of a terrible crime. When one of the party dies suddenly they realise they may be harbouring a murderer among their number.",  
                'gambar'       => "9781645054399.jpg",  
                'harga'        => 190000,  
                'discount'     => 0,  
                'jumlah_halaman'=> 300,  
                'berat'        => 312,  
                'qty'          => 15,  
                'slug'         => "i-had-that-same-dream-again",
                'category_id'  => 6,
            ],
            [
                'judul'        => "Death on the Nile",  
                'penulis'      => "Agatha Christie",  
                'penerbit'     => "HarperCollins Publishers",  
                'deskripsi'    => "The tranquillity of a cruise along the Nile is shattered by the discovery that Linnet Ridgeway has been shot through the head. She was young, stylish and beautiful, a girl who had everything - until she lost her life. Hercule Poirot recalls an earlier outburst by a fellow passenger: 'I'd like to put my dear little pistol against her head and just press the trigger.' Yet in this exotic setting nothing is ever quite what it seems...",  
                'gambar'       => "9780007527557.jpg",  
                'harga'        => 120000,  
                'discount'     => 70,  
                'jumlah_halaman'=> 384,  
                'berat'        => 260,  
                'qty'          => 5,  
                'slug'         => "death-on-the-nile",
                'category_id'  => 3,
            ],
            [
                'judul'        => "The Eminence in Shadow, Vol. 1",  
                'penulis'      => "Daisuke Aizawa",  
                'penerbit'     => "Little, Brown & Company",  
                'deskripsi'    => "Shadowbrokers are those who go unnoticed, posing as unremarkable people when in truth, they control everything from behind the scenes. Sid wants to be some just like that more than anything, and something as insignificant as boring reality isn't going to get in his way! He trains in secret every single night, preparing for his eventual rise to power-only to denied his destiny by a run of the mill yet deadly traffic accident. But when he wakes up in a another world and suddenly finds himself at the head of an actual secret organization doing battle with evil in the shadows, he'll finally get a chance to act out all of his delusional fantasies!",  
                'gambar'       => "9781975359058.jpg",  
                'harga'        => 350000,  
                'discount'     => 20,  
                'jumlah_halaman'=> 224,  
                'berat'        => 381,  
                'qty'          => 20,  
                'slug'         => "and-then-there-were-none",
                'category_id'  => 1,
            ],
         ];

        DB::table('books')->insert($data);
    }
}
